
service: victoria-authentication
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action: "dynamodb:Query"
      Resource: "arn:aws:dynamodb:*:*:table/VictoriaMemberAccepter"
    - Effect: "Allow"
      Action: "dynamodb:Query"
      Resource: "arn:aws:dynamodb:*:*:table/VictoriaAuditTrail"
    - Effect: "Allow"
      Action: "dynamodb:PutItem"
      Resource: "arn:aws:dynamodb:*:*:table/VictoriaAuditTrail"
    - Effect: "Allow"
      Action: "secretsmanager:GetSecretValue"
      Resource: "arn:aws:secretsmanager:*:*:secret:victoria-security-secrets-hPswIu"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  authorisor:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: authenticate
          method: post

#    Define function environment variables here
#    environment:
#      variable2: value2

resources:
  Resources:

    memberTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VictoriaMemberAccepter
        AttributeDefinitions:
          - AttributeName: member_id
            AttributeType: S
        KeySchema:
          - AttributeName: member_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    auditTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VictoriaAuditTrail
        AttributeDefinitions:
          - AttributeName: member_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: member_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

